sudo: true
language: c
compiler:
    - gcc
    - clang
env:
    global:
        - MBEDTLS_VER=2.4.0
before_install:
    - wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
    - tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
    - pushd mbedtls-$MBEDTLS_VER
    - make SHARED=1
    - sudo make install
    - popd
    # Load cached docker images
    - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
addons:
    apt:
        packages:
            - autoconf
            - autotools-dev
            - libudns-dev
            - libev-dev
            - asciidoc
            - xmlto
script:
    - ./autogen.sh
    - ./configure && make
    - cd build && cmake ../ && make
branches:
    only:
        - master
notifications:
    recipients:
        - max.c.lv@gmail.com
    email:
        on_success: change
        on_failure: always
