language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - autoconf
            - autotools-dev
            - libudns-dev
            - libev-dev
            - libsodium-dev
            - asciidoc
            - xmlto
script:
    - ./autogen.sh
    - ./configure && make
branches:
    only:
        - master
notifications:
    recipients:
        - max.c.lv@gmail.com
    email:
        on_success: change
        on_failure: always
